name: navigationapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  firebase_core: ^2.28.0
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  connectivity_plus: ^6.0.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
