name: navigationapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  animated_expandable_fab: ^0.0.3
  # connectivity_plus: ^6.0.1
  dio: ^5.4.1
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  flutter_expandable_fab: ^2.0.0
  flutter_screenutil: ^5.9.1
  get: ^4.6.6
  google_maps_flutter: ^2.6.1
  # http: ^1.0.0
  http: ^0.13.1
  intl: ^0.19.0
  lottie: ^3.0.0
  file_picker: ^8.0.3
  image_picker: ^1.1.1
  firebase_storage: ^11.7.7
  geolocator: ^12.0.0
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/animations/
