// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_LrcsqyvTSK-_Mc6O_TAJEIWYNd0NSnk',
    appId: '1:598144588382:web:07c4bfb542d7a875e772cf',
    messagingSenderId: '598144588382',
    projectId: 'navigationapp-74b1f',
    authDomain: 'navigationapp-74b1f.firebaseapp.com',
    storageBucket: 'navigationapp-74b1f.appspot.com',
    measurementId: 'G-M795NCB7D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwNOr6b8t2kawjybp3mEzzwnwmJbj6G1M',
    appId: '1:598144588382:android:a24814862951dae5e772cf',
    messagingSenderId: '598144588382',
    projectId: 'navigationapp-74b1f',
    storageBucket: 'navigationapp-74b1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHx-FXZF_yCenieEVEau7xSXVjtfkYnZY',
    appId: '1:598144588382:ios:92f8136a225c6883e772cf',
    messagingSenderId: '598144588382',
    projectId: 'navigationapp-74b1f',
    storageBucket: 'navigationapp-74b1f.appspot.com',
    iosBundleId: 'com.metehanozden.navigationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHx-FXZF_yCenieEVEau7xSXVjtfkYnZY',
    appId: '1:598144588382:ios:7ed56257e9e77b8be772cf',
    messagingSenderId: '598144588382',
    projectId: 'navigationapp-74b1f',
    storageBucket: 'navigationapp-74b1f.appspot.com',
    iosBundleId: 'com.example.navigationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_LrcsqyvTSK-_Mc6O_TAJEIWYNd0NSnk',
    appId: '1:598144588382:web:61c0f07901e71453e772cf',
    messagingSenderId: '598144588382',
    projectId: 'navigationapp-74b1f',
    authDomain: 'navigationapp-74b1f.firebaseapp.com',
    storageBucket: 'navigationapp-74b1f.appspot.com',
    measurementId: 'G-LLLBE2WXWB',
  );
}
